### ISSUE TITLE
Everything is invisible

### ISSUE THREAD

**Issue by Henry-Hiles** [CrackedMatter/mcpelauncher-materialbinloader#1]
Hello! This seems super cool, but when I use a shader resource pack with this mod, all blocks are invisible. I tried with just this or this plus https://github.com/GameParrot/mcpelauncher-shadersmod, but I can't get it to work. Any help would be appreciated, thanks!

**Comment by Henry-Hiles** [comment]
I'm on 1.21.31.04 if it matters, and I've tried YSS RD, Newb X Legacy, and BSBE.

**Comment by faizul726** [comment]
@Henry-Hiles if blocks are invisible that means the shader is working.

for yss you have to use beta2 from there discord server https://discord.gg/yss
and for newb use v15.53 beta or above https://github.com/devendrn/newb-x-mcbe/releases/tag/v15-dev

since BSBE isn't updated in a while you can use this to update: https://github.com/mcbegamerxx954/material-updater

hope this helps.

**Comment by Henry-Hiles** [comment]
Yep thank you, I solved it last night! The issue is that YSS shaders said tat they had beta 2 on their website but even though the filename also said beta 2 it was actually beta 1. Thanks!
